name: SwiftLint


on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/swiftlint.yml'
      - 'Instagram-Clone/.swiftlint.yml'
      - 'Instagram-Clone/**/*.swift'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/swiftlint.yml'
      - 'Instagram-Clone/.swiftlint.yml'
      - 'Instagram-Clone/**/*.swift'
      

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run Swiftlint
        run: swiftlint --config Instagram-Clone/.swiftlint.yml
